# Generated by Django 3.2.4 on 2022-08-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_password',
            new_name='app_password',
        ),
    ]
