# Generated by Django 3.2.4 on 2022-08-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_password',
        ),
    ]
