# Generated by Django 3.2.4 on 2022-08-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0006_auto_20220820_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppassword',
            name='app_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
